# Generated by Django 3.2.5 on 2021-07-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', editable=False, max_length=180, verbose_name='Заголовок')),
                ('image', models.CharField(blank=True, default='', editable=False, max_length=250, verbose_name='Изображение')),
                ('url', models.CharField(db_index=True, max_length=191, unique=True, verbose_name='Url')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('start_price', models.PositiveIntegerField(blank=True, db_index=True, default=0, editable=False, verbose_name='Начальная цена')),
                ('price', models.PositiveIntegerField(blank=True, db_index=True, default=0.0, editable=False, verbose_name='Цена')),
                ('old_price', models.PositiveIntegerField(blank=True, db_index=True, default=0.0, editable=False, verbose_name='Старая цена')),
                ('content', models.TextField(blank=True, default='', editable=False, verbose_name='Описание')),
                ('price_down', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Подешевел')),
                ('price_up', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Подорожал')),
                ('is_views', models.BooleanField(default=False, editable=False, verbose_name='Просмотрено')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'ordering': ['-edit_date'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('price', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Цена')),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'db_table': 'price',
                'ordering': ['pub_date'],
            },
        ),
    ]
