# Generated by Django 3.2.4 on 2021-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, editable=False, max_length=180, verbose_name='Заголовок')),
                ('url', models.CharField(blank=True, db_index=True, max_length=191, verbose_name='Ссылка на страницу товара')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True, verbose_name='ЧПУ URL')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
                'ordering': ['-edit_date'],
            },
        ),
    ]
