# Generated by Django 3.2.4 on 2021-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=191, unique=True, verbose_name='Ссылка на страницу товара'),
        ),
    ]
