# Generated by Django 3.2.4 on 2021-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210618_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, editable=False, max_length=180, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=191, unique=True, verbose_name='Url'),
        ),
    ]
