# Generated by Django 3.2.4 on 2021-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210618_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, editable=False, max_digits=6, verbose_name='Цена'),
        ),
    ]
