# Generated by Django 3.2.4 on 2021-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Описание'),
        ),
    ]
