# Generated by Django 3.2.4 on 2021-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, editable=False, max_digits=6, verbose_name='Цена')),
                ('product', models.ManyToManyField(editable=False, related_name='product', to='product.Product')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'db_table': 'price',
                'ordering': ['-pub_date'],
            },
        ),
    ]
