# Generated by Django 3.2.4 on 2021-06-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210621_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='Начальная цена'),
        ),
    ]
