# Generated by Django 3.2.4 on 2021-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_start_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['pub_date'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_views',
            field=models.BooleanField(default=False, editable=False, verbose_name='Просмотрено'),
        ),
    ]
