# Generated by Django 3.2.4 on 2021-06-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210622_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Начальная цена'),
        ),
    ]
