# Generated by Django 3.2.4 on 2021-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210622_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_price',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, editable=False, verbose_name='Начальная цена'),
        ),
    ]
