# Generated by Django 3.2.4 on 2021-06-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_start_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0.0, editable=False, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0.0, editable=False, verbose_name='Цена'),
        ),
    ]
